# Site settings
title: Reflections
subtitle: Musings of the unknown footballer,
email: arghasen@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My new blog on Jekyll based Github pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: arghasen
github_username:  arghasen

# Build settings
markdown: kramdown
