# Site settings
title: Reflections
tagline: Musings of the unknown footballer,
email: arghasen@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My new blog on Jekyll based Github pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arghasen.com" # the base hostname & protocol for your site
header-img: img/home-bg.jpg
twitter_username: arghasen
github_username:  arghasen
facebook_username: senargha

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
    sass_dir:          _sass
    style:            :compressed

# About/contact
author:
    name:              Argha Sen

